// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8wAFZAgNH5vTwNzk2Jb4YiBXRXwt7wV0',
    appId: '1:859756164358:web:a4d2a6df86dc55bc131a87',
    messagingSenderId: '859756164358',
    projectId: 'fir-practice-code',
    authDomain: 'fir-practice-code.firebaseapp.com',
    storageBucket: 'fir-practice-code.appspot.com',
    measurementId: 'G-C4YRRF6FLD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3IfOiK85M4jsdLq-i8Zqza7SVLZPz5vM',
    appId: '1:859756164358:android:96fab358c300ba1b131a87',
    messagingSenderId: '859756164358',
    projectId: 'fir-practice-code',
    storageBucket: 'fir-practice-code.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDp6gGK5HA0PXnxWQBKKKyM9gujeA11UOo',
    appId: '1:859756164358:ios:2ce811f6ed0b01a3131a87',
    messagingSenderId: '859756164358',
    projectId: 'fir-practice-code',
    storageBucket: 'fir-practice-code.appspot.com',
    iosBundleId: 'com.aabis.firebasePracticeCode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDp6gGK5HA0PXnxWQBKKKyM9gujeA11UOo',
    appId: '1:859756164358:ios:edbfd7175e748093131a87',
    messagingSenderId: '859756164358',
    projectId: 'fir-practice-code',
    storageBucket: 'fir-practice-code.appspot.com',
    iosBundleId: 'com.aabis.firebasePracticeCode.RunnerTests',
  );
}
